### PR TITLE
Add the non-decreasing array solution

### PR DESCRIPTION
**Pull request by Nimesh-21**
I added the solution of the Leetcode Non-decreasing array in the Text file format.

### CODE REVIEW

**Review by 2000shivam659 — CHANGES_REQUESTED** [review]
write the main code as well as explain your solution in explanation and also as a comment line in between code.

**Comment by Nimesh-21** [comment]
I updated the comments. Please see through it or should I make another Pull request?

**Review by 2000shivam659 — APPROVED** [review]

**Comment by 2000shivam659** [comment]
Good one but before pushing another one you can make changes to the previous one or you should delete the previous one, that's the correct way of doing it.

**Comment by Nimesh-21** [comment]
Ohk sir, actually I am new to open source so I am still learning.

**Pull request merged**
